
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Petek
 */
public class OrderApp extends javax.swing.JFrame {
    Map<String, Integer> orders = new LinkedHashMap<>();
    
    
    /**
     * Creates new form OrderApp
     */
    public OrderApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TurkishKebabCheck = new javax.swing.JCheckBox();
        KunefeCheck = new javax.swing.JCheckBox();
        SaladCheck = new javax.swing.JCheckBox();
        AyranCheck = new javax.swing.JCheckBox();
        show_orders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Application");

        jLabel1.setText("MENU ");

        TurkishKebabCheck.setText("Turkish Kebab- 40$");

        KunefeCheck.setText("Kunefe - 20$");

        SaladCheck.setText("Salad - 5$");

        AyranCheck.setText("Ayran - 2$");

        show_orders.setText("Show  Orders");
        show_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_ordersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaladCheck)
                    .addComponent(KunefeCheck)
                    .addComponent(TurkishKebabCheck)
                    .addComponent(show_orders)
                    .addComponent(AyranCheck)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TurkishKebabCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KunefeCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaladCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AyranCheck)
                .addGap(18, 18, 18)
                .addComponent(show_orders)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void show_orders() {
        String message = "";
        int total = 0;
        if (orders.isEmpty()) {
            message = "You don't have any orders.";
        }
        else {
            message += "The orders : \n";
            
            for (Map.Entry<String,Integer> entry: orders.entrySet()) {
                message += entry.getKey() + "\n";
                total += entry.getValue();
            }
            message += "Sum : " + total + " $";
        }
        JOptionPane.showMessageDialog(this, message);
        
    }
    private void show_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_ordersActionPerformed
        if (TurkishKebabCheck.isSelected()) {
            orders.put("TurkishKebab", 40);
            
        }
        else {
            orders.remove("TurkıshKebab");
            
        }
        if (KunefeCheck.isSelected()) {
            orders.put("Kunefe", 20);
            
        }
        else {
            orders.remove("Kunefe");
            
        }
        if (SaladCheck.isSelected()) {
            orders.put("Salad", 5);
            
        }
        else {
            orders.remove("Salad");
            
        }
        if (AyranCheck.isSelected()) {
            orders.put("Ayran", 2);
            
        }
        else {
            orders.remove("Ayran");
            
        }
        show_orders();
        
    }//GEN-LAST:event_show_ordersActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AyranCheck;
    private javax.swing.JCheckBox KunefeCheck;
    private javax.swing.JCheckBox SaladCheck;
    private javax.swing.JCheckBox TurkishKebabCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton show_orders;
    // End of variables declaration//GEN-END:variables
}
